version: '3.8'

services:
  fraud-detection-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5000"
    volumes:
      - ./fraud_predictions.db:/app/fraud_predictions.db
      - ./model:/app/model
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fraud-detection-api
    environment:
      - API_BASE_URL=http://fraud-detection-api:5000
    restart: unless-stopped