version: '3.8'

services:
  jupyter-training:
    build:
      context: .
      dockerfile: Dockerfile.training
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./model:/workspace/model
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=fraud_detection_training
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Starting Jupyter Lab for Fraud Detection Training...' &&
        echo 'Access at: http://localhost:8888' &&
        echo 'Token: fraud_detection_training' &&
        echo '' &&
        echo 'Instructions:' &&
        echo '1. Open Training.ipynb' &&
        echo '2. Run cells 1-25 for EDA' &&
        echo '3. Run cells 26-59 for model training' &&
        echo '4. Model will be saved to model/fraud_model.joblib' &&
        echo '' &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=fraud_detection_training
      "
    restart: unless-stopped